// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxodafvamqptchgtqxjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4b2RhZnZhbXFwdGNoZ3RxeGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzgyMDcsImV4cCI6MjA3MzYxNDIwN30.qw78Yd3YDmWPJuqe-uB1_XCcCXIZxnnB3TqPzwg9J3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});